{% set name = "python-casacore" %}
{% set version = "3.2.0" %}
{% set sha256 = "d48e6202831ef22983961aa14c82294325f71b2fd3e108efaa3c1ca99b7505b5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost
    - casacore >=3.2.*
    - numpy
    - pip
    - python
    - setuptools
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - casacore
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://casacore.github.io/python-casacore/
  license: GPL-2.0-or-later
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: 'Python bindings for casacore, a library used in radio astronomy'

extra:
  recipe-maintainers:
    - pkgw
