{% set name = "python-casacore" %}
{% set version = "2.2.1" %}
{% set sha256 = "76075aa4add4f18b29d474ea3e155bce2d0688ed247ca1ce91a8106f08377bc5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/casacore/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - boost-python.patch

build:
  number: 2
  detect_binary_files_with_prefix: true
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost
    - casacore >=2.4.*
    - numpy
    - python
    - setuptools
  run:
    - boost
    - casacore >=2.4.*
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - casacore
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://casacore.github.io/python-casacore/
  license: GPLv2
  license_file: LICENSE
  summary: 'Python bindings for casacore, a library used in radio astronomy'

extra:
  recipe-maintainers:
    - pkgw
