{% set name = "python-casacore" %}
{% set version = "3.5.2" %}
{% set sha256 = "ad70c8e08893eec928b3e38c099bda8863f5aa9d099fd00694ad2b0d48eba08f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 5
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - libboost-python-devel
    - casacore >=3.2.*
    - numpy
    - pip
    - python
    - setuptools
  run:
    - python
    - six

test:
  imports:
    - casacore
  commands:

about:
  home: http://casacore.github.io/python-casacore/
  license: GPL-2.0-or-later
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Python bindings for casacore, a library used in radio astronomy

extra:
  recipe-maintainers:
    - pkgw
