{% set name = "python-casacore" %}
{% set version = "3.5.0" %}
{% set sha256 = "47ac85d47051074d64415414212c8c2cfcb49a2037f5c3d78f71ab5b162d1e8b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost
    - casacore >=3.2.*
    - numpy
    - pip
    - python
    - setuptools
  run:
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('numpy') }}
    - python
    - six

test:
  imports:
    - casacore
  commands:

about:
  home: http://casacore.github.io/python-casacore/
  license: GPL-2.0-or-later
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Python bindings for casacore, a library used in radio astronomy

extra:
  recipe-maintainers:
    - pkgw
