{% set name = "python-casacore" %}
{% set version = "3.4.0" %}
{% set sha256 = "f654781292308de70c037981f5f7f5aeb02cf980a6f1367d1c294e7b4fca42ce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost
    - casacore >=3.2.*
    - numpy
    - pip
    - python
    - setuptools
  run:
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('numpy') }}
    - python
    - six

test:
  imports:
    - casacore
  commands:

about:
  home: http://casacore.github.io/python-casacore/
  license: GPL-2.0-or-later
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Python bindings for casacore, a library used in radio astronomy

extra:
  recipe-maintainers:
    - pkgw
