# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_NPY=111  CONDA_PY=27
    - CONDA_NPY=112  CONDA_PY=27
    - CONDA_NPY=111  CONDA_PY=35
    - CONDA_NPY=112  CONDA_PY=35
    - CONDA_NPY=111  CONDA_PY=36
    - CONDA_NPY=112  CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "FOZm3a+WUpPAEfZWRLk7yPwxXMlSZgNvpWkscQlg3gcFad9BQV2E6RPT9KEMmZhCK6WkKRGCrZIsK7BxGDRI6ZlanX2bVa7IIRKxpnirABsyphlWCHRhPmsrOL07haaxFi1R6sRRSAG9mPd5wiE8gjXWNgs4uaQGfLE7huFIq+2ZQ3/lONt7qcU9/AUCDOS9ZevKChsY98XDLQrfjT19j7d4ERYqyDNh1rJ4bv51sOW8xcwQoRWAdQV1YC5bPB4YvMRToB4AG8KyOMBwOOdV6R0DyH8VeIHYQaumOfxXAKMZsJITCCmngqPZ2frOTkRqJrcZpakghIgWlyccDnav5mtD4agMUl/oK+DPyblY2vi4KGu4pu+LpF7H8TzDxoyfI5aYl68Szk1B+CYDsJBa6Jcr0G/NAWq9MvsWZcMnPG/oz1MMbjYzHdDiR+1FJsIzCj+hBCwWEdv98sEGbGvHdfclUuN+ljh7omm2LwuQ6Yd1DWGE7NFCJxZ3RU4mLLWJv//oK7bQzuL7+MMn5MpEMRKS7gW0IN3B6efHlIeQUzjM2F3S9rjzwrBXvMoGGn9WdkTqb8SVe0hvDIPOzcS2UWjN9EodyZOLDnlzeLEPQyHvnaaRRfygM9aVc9go/v5PAuW/dFsLVrS+U73InnQ3lHujhT2xliC5ZrVAem5Ysm0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
