travis:
  secure:
    BINSTAR_TOKEN: Mtub0AcaSB8xGDXarv+D3qMXfaM9t5FrKWOTz5Dcj8Fymk5sMCUvKeUnXrQ2qst8pq2rjwr+3yElJ9jNpkGHtQTAERUupD5W5lwRrZQMI/VWrpo+GPDG2gQEFWu23wu3uvp+ajO7IdU/4qqi2Fh4RkeYht5OCTznYEEi/erzRfGEXazk2tAEzwN1zHA/lshUsPwF87YJfDPYtyPA3eJW3qgUjbpAAEIx9S2Pd2PQgHBZG5xFDSpcvbkTSaGo1EsozPCDtlU8pr0x8/hIVmQVRmf+nT9QUyeFajhFlTXRT/a2URwTEgfqDG5n9A+Zhwave2mWplV+/qzp7aGnfmTAez6Kxz7a5nMczOdO3MGZD2pUXtKRN1BDIDi21N+QBuxjYLydGlTYJ8yz6gIqC0IeA3sqn7XiMvKMYVSJ5Lgz+liWKIA3rd1fMJVaAg74cWoHL1i0sGNJEz6t+XVRsm4mSsvKPDbhFY68UCs6oPaFNIoiz6/d9dzVILEyMgoIO+6xenHSO6QbIjl0jwb08OknY0hyEysjZTmA2dVaN6gDQnlvDgBApe7tp+/2CrOm8fxqxfvPj7nUvej2PvSW28fmHhkikoeMRS+JbJ4uIXbuqtrqbV8+ED++U1by0uxs0hXnSKII5g+3FLkCThXji5JTpmrgDDJlzy/eQHN77jA3ytw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
